<?php
// Konfiguracja popupów formularzy - przenieść do kontroolera...

$data1 = [
    'popup_id' => 'hair',
    'element_title' => 'Wybierz fryzurę',
    'color_title' => 'Wybierz kolor włosów',
    'show_random_element' => false,
    'elements' => range(1,14),
    'colors' => isset($custom_colors) ? $custom_colors : null,
    'show_random_color' => true,
];


$data2 = [
    'popup_id' => 'blouse',
    'element_title' => 'Wybierz wzór bluzki',
    'color_title' => 'Wybierz kolor bluzki',
    'show_random_element' => false,
    'elements' => range(1,8),
    'colors' => isset($custom_colors) ? $custom_colors : null,
    'show_random_color' => true,
];


$data3 = [
    'popup_id' => 'eye',
    'element_title' => 'Wybierz oczy',
    'color_title' => 'Wybierz kolor oczu',
    'show_random_element' => false,
    'elements' => range(1,6),
    'colors' => null,
    'show_random_color' => false,
];


$data4 = [
    'popup_id' => 'eyeglasses',
    'element_title' => 'Wybierz okuary',
    'color_title' => 'Wybierz kolor okularów',
    'show_random_element' => true,
    'elements' => range(1,4),
    'colors' => isset($custom_colors) ? $custom_colors : null,
    'show_random_color' => true,
];



?>

<link rel="stylesheet" href="/assets/css/bootstrap-image-checkbox.css"/>
<style>
	body {
		background-color: #FFC107;
		color: #333;
	}



	h1 {
		margin-bottom: 1rem;
		margin-top: 1rem;
	}

	.text-highlight {
		color:#FFC107;
	}

	.alert-custom {
		border: solid 1px #d43226;
		background: #FF5722;
	}

	.alert-custom .alert-link,
	.alert-custom .alert-link:hover {
		color: #fff;
	}

	.hidden {
		display: none;
	}



	/* Custom colors */
	.custom_bg_0 {background-color: #ffffff}

	<?php
if(isset($custom_colors)) {
	foreach($custom_colors as $id => $v) {
		?>
	.custom_bg_<?php echo $id; ?> {background-color: <?php echo $v; ?>}

	.custom_color_<?php echo $id; ?> {color: <?php echo $v; ?>}

	<?php
	}
}
 ?>

	.custom_bg_43 .svg_checkmark {
		fill: #d8d8d8 !important;
	}


	/* POPUP */
	.custom_popup {
		z-index:10;
		position: absolute;
		border: solid 1px #025f56;
		background: #009688;
		top: 10px;
		width: 90%;
		margin: auto 5%;
		box-shadow: 2px 2px 2px #000;
	}

	.popup_close {
		cursor: pointer;
		position: absolute;
		right: 2px;
		top: 2px;
		z-index: 15;
		background-color:#FFC107;
	}

	.popup_close:hover {
		transform: scale(.9);
		/*background: #ff800a;*/
		z-index: 2;
		box-shadow: 2px 2px 2px #000;
	}




	.palette-container {
		width: 90%;
		padding: 10px;
		margin: 10px auto;
		display: flex;
		flex-flow: row wrap;
		justify-content: flex-start;
	}

	.palette-container .item {
		flex-basis: 20%;
		height: 100px;
		margin: 0;
		transition: 1s;
		position: relative;
		cursor: pointer;
	}

	.palette-container .item:hover {
		transform: scale(.9);
		z-index: 2;
		box-shadow: 2px 2px 2px #000;
	}



	/* HIDE RADIO */
	.palette-container .item .palette-custom-radio {
		position: absolute;
		opacity: 0;
		width: 0;
		height: 0;
	}

	/* IMAGE STYLES */
	.palette-container .item  svg {
		position: absolute;
		top: 10px;
		left: 10px;
	}

	/* CHECKED STYLES */

	.palette-container .item .palette-custom-radio ~ svg {
		opacity: 0;
		z-index: 3;
	}

	.palette-container .item .palette-custom-radio:checked ~ svg {
		opacity: 1;
	}

	.palette-container .item .item-label {
		width: 100%;
		height: 100%;
		position: absolute;
		z-index: 5;
		cursor: pointer;
		text-align: center;
		line-height: 1.5;
		padding: 2% 0 0;
		font-weight: 700;
		font-size: 2em;
		color: #FF5722;
	}

	.palette-container .item .item-label .img {
		height:90px;
	}


	/* CUSTOMIZE PALETTES */

	.palette-container.palette-container-colors .item {
		height: 55px;
		flex-basis: 12.5%;
	}
	.palette-container.palette-container-colors .item .item-label {
		height: 55px;
	}
	.palette-container.palette-container-colors .item svg {
		height: 40px;
	}


	@media screen and (max-width: 768px) {
		.palette-container .item {
			flex-basis: 33.33%;
		}
		.palette-container.palette-container-colors .item {
			flex-basis: 33.33%;
		}
		.palette-container.palette-container-colors .item .item-label {
			font-size: 1em;
		}
	}


	/* CARDS */


	.card{
		border: solid 5px transparent;
		transition: .5s;
		cursor:pointer;
	}

	.card.card-active,
	.card:hover{
		border: solid 5px #009688;

		transform: scale(1.05);
		z-index: 2;
		box-shadow: 2px 2px 2px #000;
	}

	.card .step_number {
		position: absolute;
		font-weight: 700;
		font-size: 2em;
		display: block;
		text-align: center;
		width: 100%;
	}


	/* BUTTONS */
	.btn-group-lg>.btn.btn_choose_element,
	.btn-lg.btn_choose_element {
		background-position: 2px 2px;
		background-repeat: no-repeat;
		background-size: 39px 43px;
		padding-left: 50px;
	}
	.btn_color{background-image: url('/assets/images/choose_color.svg');}
	.btn_hair{background-image: url('/assets/images/choose_hair.svg');}
	.btn_eye{background-image: url('/assets/images/choose_eye.svg');}
	.btn_eyeglasses{background-image: url('/assets/images/choose_eyeglasses.svg');}
	.btn_blouse{background-image: url('/assets/images/choose_blouse.svg');}
	.btn_beard{background-image: url('/assets/images/choose_beard.svg');}



	/* PAGE COLOR THEMES */
	/*
	body.theme-green{
		background-color: #a1fb39;
	}
	body.theme-green .alert-custom {
		border-color: #d43226;
		background-color: #FF5722;
	}
	body.theme-blue .alert-custom .alert-link,
	body.theme-blue.alert-custom .alert-link:hover {
		color:#00BCD4;
	}
	body.theme-green .custom_popup {
		border-color: #025f56;
		background-color: #009688;
	}
	body.theme-green .card.card-active,
	body.theme-green .card:hover{
		border-color: #009688;
	}
	body.theme-green .btn-warning{
		color: #212529;
		background-color: #a1fb39;
		border-color: #a1fb39;
	}
	body.theme-green .btn-warning:hover {
		color: #212529;
		background-color: #a1fb39;
		border-color: #a1fb39;
	}
	body.theme-green .popup_close {
		background-color:#a1fb39;
	}
	body.theme-blue .text-highlight {
		color:#a1fb39;
	}



	body.theme-blue{
		background-color: #00BCD4;
	}
	body.theme-blue .alert-custom {
		border-color: #FF9800;
		background-color: #FFEB3B;
	}
	body.theme-blue .alert-custom .alert-link,
	body.theme-blue.alert-custom .alert-link:hover {
		color:#00BCD4;
	}
	body.theme-blue .custom_popup {
		border-color: #025f56;
		background-color: #009688;
	}
	body.theme-blue .card.card-active,
	body.theme-blue .card:hover{
		border-color: #009688;
	}
	body.theme-blue .btn-warning{
		color: #212529;
		background-color: #00BCD4;
		border-color: #00BCD4;
	}
	body.theme-blue .btn-warning:hover {
		color: #212529;
		background-color: #00BCD4;
		border-color: #00BCD4;
	}
	body.theme-blue .popup_close {
		background-color:#00BCD4;
	}
	body.theme-blue .text-highlight {
		color:#00BCD4;
	}
*/


</style>
<div class="container">

	<h1 class="text-center"><?php echo $title; ?></h1>

    <?php echo validation_errors(); ?>

    <?php $this->load->view('notifications.phtml'); ?>

    <?php //echo $avatar->getCssStyle(); ?>

	<div id="wrapper">

		<div class="alert text-white bg-dark" role="alert">
			Wyczaruj swojego awatarka w 5 krokach.<br>Awatara możesz używać w serwisach społecznościowych, czatach, komunikatorach. Wszędzie tam, gdzie masz ochotę.
		</div>

		<div class="form mb-3">
		<form id="form-wizard" method="post">

			<div class="row">

				<div class="col mb-3">
					<div id="hair_card" class="card h-100 text-white bg-dark js-card-clickable" data-target="hair_palette">
						<span class="step_number text-highlight">Krok 1</span>
						<img class="card-img-top p-3" src="/assets/images/choose_hair.svg" alt="Choose hair">
						<div class="card-body d-flex flex-column">
							<h5 class="card-title mt-auto">Fryzury</h5>
							<p class="card-text mt-auto">Wybierz fryzurę i kolor włosów swojej postaci</p>
							<a href="#" class="btn btn-warning btn-block mt-auto js-open-popup" data-target="hair_palette">Wybieram</a>
						</div>
					</div>
				</div>

				<div class="col mb-3">
					<div id="eye_card" class="card h-100 text-white bg-dark js-card-clickable" data-target="eye_palette">
						<span class="step_number text-highlight">Krok 2</span>
						<img class="card-img-top p-3" src="/assets/images/choose_eye.svg" alt="Choose hair">
						<div class="card-body d-flex flex-column">
							<h5 class="card-title mt-auto">Oczy</h5>
							<p class="card-text mt-auto">Wybierz oczy dla swojej postaci</p>
							<a href="#" class="btn btn-warning btn-block mt-auto js-open-popup" data-target="eye_palette">Wybieram</a>
						</div>
					</div>
				</div>

				<div class="col mb-3">
					<div id="blouse_card" class="card h-100 text-white bg-dark js-card-clickable" data-target="blouse_palette">
						<span class="step_number text-highlight">Krok 3</span>
						<img class="card-img-top p-3" src="/assets/images/choose_blouse.svg" alt="Choose hair">
						<div class="card-body d-flex flex-column">
							<h5 class="card-title mt-auto">Bluzki</h5>
							<p class="card-text mt-auto">Wybierz rodzaj i kolor bluzki swojej postaci</p>
							<a href="#" class="btn btn-warning btn-block mt-auto js-open-popup" data-target="blouse_palette">Wybieram</a>
						</div>
					</div>
				</div>

				<div class="col mb-3">
					<div id="eyeglasses_card" class="card h-100 text-white bg-dark js-card-clickable" data-target="eyeglasses_palette">
						<span class="step_number text-highlight">Krok 4</span>
						<img class="card-img-top p-3" src="/assets/images/choose_eyeglasses.svg" alt="Choose eyeglasses">
						<div class="card-body d-flex flex-column">
							<h5 class="card-title mt-auto">Okulary</h5>
							<p class="card-text mt-auto">Wybierz rodzaj i kolor okularów swojej postaci</p>
							<a href="#" class="btn btn-warning btn-block mt-auto js-open-popup" data-target="eyeglasses_palette">Wybieram</a>
						</div>
					</div>
				</div>




				<div class="col mb-3">
					<div id="finish_card" class="card h-100 text-white bg-dark">
						<span class="step_number text-highlight">Krok 5</span>
						<img class="card-img-top p-3" src="/assets/images/choose_avatar.svg" alt="Choose avatar">
						<div class="card-body d-flex flex-column">
							<h5 class="card-title mt-auto">Gotowe</h5>
							<p class="card-text mt-auto">Teraz możesz zobaczyć swoją postać</p>
						<?php /*	<!-- <button type="submit" class="btn btn-warning btn-lg btn-block mt-auto js_scroll" data-target="preview">Pokaż awatarka</button>--> */ ?>
							<a href="#" class="btn btn-warning btn-block mt-auto">Pokaż awatarka</a>
						</div>
					</div>
				</div>

			</div>


		</form>

		</div> <!-- /.form -->



        <?php //echo $svg_image_data; ?>

		<div id="preview" class="row">
			<div class="col-md-3 mb-3 text-center" id="preview">
				<img src="" class="img-fluid rounded-circle">
			</div>
			<div class="col-md-9" id="result_url">
				<div class="alert alert-custom hidden" role="alert">Adres URL do Twojego awatara:<br>
					<small>(Kliknij w adres, aby otworzyć obrazek w nowym oknie)</small><br>
					<span class="text-break"></span>
				</div>
			</div>
		</div>

	</div>

</div>


<?php
// Popupy z formularzami
$this->load->view('popup_items.phtml', $data1);
$this->load->view('popup_items.phtml', $data2);
$this->load->view('popup_items.phtml', $data3);
$this->load->view('popup_items.phtml', $data4);
?>

<div class="m-5"></div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-3.4.1.min.js"><\/script>')</script>

<script>
	var module_path = '<?php echo $module_path; ?>'
	var module_url = '<?php echo $module_url; ?>draw'


	$(document).ready(function () {

		function openPopup(target) {

			$('.custom_popup').addClass('hidden')
			$('#'+target).removeClass('hidden')

			$([document.documentElement, document.body]).animate({
				scrollTop: $("#"+target).offset().top - 10
			}, 400);
		}

		function getRandomAvatar(){
			$.ajax({
				method: 'GET',
				url: module_url+'Random',
			})
			.done(function (data) {
				// console.log(data)
				let image_url = '<?php echo base_url("images/avatars/"); ?>'+data;
				$('#preview img').attr('src', image_url)

				$('#result_url span').html('<a href="'+image_url+'" class="alert-link" target="_blank">'+image_url+'</a>')
				$('#result_url .alert').removeClass('hidden')


			})
			.always(function() {
				//openPopup('preview');

			});
		}

		getRandomAvatar();

		// Aby nie submitować dwukrotnie
		$("#finish_card a").on('click', function(e){
			e.preventDefault();
		})
		$('#form-wizard').on('submit', function (e) {
			e.preventDefault()

				<?php
			/*
			let url = 'http://test3.melma.pl/avatars/core.php';
			let n = $('#number').val();
			$.get(url, { n: n }).done(function (data) {
				// $('#css').html(n + '! = ' + data + '<br>').addClass('alert alert-success')

				$('#css').html(data);
			});
			*/
			?>

			let eyeglasses = $('input[name=\'radio_eyeglasses\']:checked').val()
			let hair = $('input[name=\'radio_hair\']:checked').val()
			let hair_color = $('input[name=\'radio_hair_color\']:checked').val()
			let eyeglasses_color = $('input[name=\'radio_eyeglasses_color\']:checked').val()
			let blouse = $('input[name=\'radio_blouse\']:checked').val()
			let blouse_color = $('input[name=\'radio_blouse_color\']:checked').val()
			let eye = $('input[name=\'radio_eye\']:checked').val()

			$.ajax({
				method: 'POST',
				url: module_url,
				data: {
					hair: hair,
					blouse: blouse,
					eye: eye,
					hair_color: hair_color,
					blouse_color: blouse_color,
					eyeglasses: eyeglasses,
					eyeglasses_color: eyeglasses_color,
				},
				// data: $(this).serialize(),
				// dataType:"json",
			})
			.done(function (data) {
				// console.log(data)
				let image_url = '<?php echo base_url("images/avatars/"); ?>'+data;
				$('#preview img').attr('src', '/images/avatars/' + data)

				$('#result_url span').html('<a href="'+image_url+'" class="alert-link" target="_blank">'+image_url+'</a>')
				$('#result_url .alert').removeClass('hidden')


			})
			.always(function() {
				openPopup('preview');

			});

		})


		$('.popup_close').on('click', function (e) {
			$(this).parent().addClass('hidden')
		})

		$('.js-close').on('click', function (e) {
			$('#'+$(this).data('close')).addClass('hidden')

			let target = $(this).data('target');
			openPopup(target)
			$('.card').removeClass('card-active')
			$('#'+target).addClass('card-active')
		})

		$('.js-open-popup,.js-card-clickable').on('click', function (e) {
			e.preventDefault();
			openPopup($(this).data('target'));
		})
		$('#finish_card').on('click', function(e){
			$('#form-wizard').submit();
		})

	})
</script>