<?php
// Konfiguracja popupów formularzy - przenieść do kontroolera...
$data = [];

$data[1] = [
    'item_active' => true,
    'item_nr' => 1,
    'item_id' => 'hair',
	'card_title' => 'Fryzury',
	'card_description' => 'Wybierz fryzurę i kolor włosów swojej postaci',
    'popup_elements' => range(1,14),
    'popup_element_title' => 'Wybierz fryzurę',
    'popup_color_title' => 'Wybierz kolor włosów',
    'popup_element_allow_random' => true,
    'popup_element_random_legend' => 'Kliknij %s aby wybierać losowo fryzury.',
    'popup_element_allow_uncheck' => true,
    'popup_element_uncheck_legend' => 'Kliknij %s aby usunąć włosy.',
    'popup_colors' => isset($custom_colors['hair']) ? $custom_colors['hair'] : null,
    'popup_color_allow_random' => true,
];

$data[2] = [
    'item_active' => true,
    'item_nr' => 2,
    'item_id' => 'blouse',
    'card_title' => 'Bluzki',
    'card_description' => 'Wybierz rodzaj i kolor bluzki swojej postaci',
    'popup_elements' => range(1,8),
    'popup_element_title' => 'Wybierz rodzaj bluzki',
    'popup_color_title' => 'Wybierz kolor bluzki',
    'popup_element_allow_random' => true,
    'popup_element_random_legend' => 'Kliknij %s aby wybierać losowo bluzki.',
    'popup_element_allow_uncheck' => false,
    'popup_element_uncheck_legend' => 'Kliknij %s aby usunąć bluzki.',
    'popup_colors' => isset($custom_colors['blouse']) ? $custom_colors['blouse'] : null,
    'popup_color_allow_random' => true,
];

$data[3] = [
    'item_active' => true,
    'item_nr' => 3,
    'item_id' => 'eye',
    'card_title' => 'Oczy',
    'card_description' => 'Wybierz rodzaj i kolor oczu dla swojej postaci',
    'popup_elements' => range(1,6),
    'popup_element_title' => 'Wybierz rodzaj oczu',
    'popup_color_title' => 'Wybierz kolor oczu',
    'popup_element_allow_random' => true,
    'popup_element_random_legend' => 'Kliknij %s aby wybierać losowo oczy.',
    'popup_element_allow_uncheck' => false,
    'popup_element_uncheck_legend' => 'Kliknij %s aby usunąć oczy.',
    'popup_colors' => isset($custom_colors['eye']) ? $custom_colors['eye'] : null,
    'popup_color_allow_random' => true,
];

$data[4] = [
    'item_active' => true,
    'item_nr' => 4,
    'item_id' => 'eyeglasses',
    'card_title' => 'Okulary',
    'card_description' => 'Wybierz rodzaj i kolor okularów swojej postaci',
    'popup_elements' => range(1,4),
    'popup_element_title' => 'Wybierz rodzaj okularów',
    'popup_color_title' => 'Wybierz kolor ramki okularów',
    'popup_element_allow_random' => true,
    'popup_element_random_legend' => 'Kliknij %s aby wybierać losowo okulary.',
    'popup_element_allow_uncheck' => true,
    'popup_element_uncheck_legend' => 'Kliknij %s aby usunąć okulary.',
    'popup_colors' => isset($custom_colors['eyeglasses']) ? $custom_colors['eyeglasses'] : null,
    'popup_color_allow_random' => true,
];

?>

<link rel="stylesheet" href="/assets/css/bootstrap-image-checkbox.css"/>
<style>
	body {
		background-color: #FFC107;
		color: #333;
	}







	/* Custom colors */
	.custom_bg_0 {background-color: #ffffff}
	.custom_bg_transparent {background-color: transparent;}

	<?php
if(isset($custom_colors)) {
	foreach($custom_colors as $element => $list) {
		foreach($list as $id => $v) {
		?>
		.custom_bg_<?php echo $element; ?>_<?php echo $id; ?> {background-color: <?php echo $v; ?>}
		.custom_color_<?php echo $element; ?>_<?php echo $id; ?> {color: <?php echo $v; ?>}
		<?php
		}
	}
}
 ?>

	.custom_bg_hair_4 .svg_checkmark,
	.custom_bg_hair_5 .svg_checkmark,
	.custom_bg_hair_15 .svg_checkmark,
	.custom_bg_eye_2 .svg_checkmark,
	.custom_bg_blouse_4 .svg_checkmark,
	.custom_bg_blouse_5 .svg_checkmark,
	.custom_bg_blouse_15 .svg_checkmark,
	.custom_bg_eyeglasses_4 .svg_checkmark,
	.custom_bg_eyeglasses_5 .svg_checkmark,
	.custom_bg_eyeglasses_15 .svg_checkmark
	{
		fill: #d8d8d8 !important;
	}


	/* POPUP */
	.custom_popup {
		z-index:10;
		position: absolute;
		border-style: solid;
		border-width: 1px;
		top: 10px;
		width: 90%;
		margin: auto 5%;
		box-shadow: 2px 2px 2px #000;
	}


	.popup_close {
		cursor: pointer;
		position: absolute;
		right: 2px;
		top: 2px;
		z-index: 15;
		background-color:#FFC107;
	}

	.popup_close:hover {
		transform: scale(.9);
		/*background: #ff800a;*/
		z-index: 2;
		box-shadow: 2px 2px 2px #000;
	}




	.palette-container {
		width: 90%;
		padding: 10px;
		margin: 10px auto;
		display: flex;
		flex-flow: row wrap;
		justify-content: flex-start;
	}

	.palette-container .item {
		flex-basis: 50%;
		height: 100px;
		margin: 0;
		transition: 1s;
		position: relative;
		cursor: pointer;
	}

	.palette-container .item:hover {
		transform: scale(1.2);
		z-index: 10;
		box-shadow: 2px 2px 2px #000;
	}

	.palette-container.palette-container-elements .item:hover {
		background-color: #FFC107;
	}

	.palette-container.palette-container-elements .palette-custom-radio:checked ~ .item-label {
		background-color: #fdbe3f;
	}



	/* HIDE RADIO */
	.palette-container .item .palette-custom-radio {
		position: absolute;
		opacity: 0;
		width: 0;
		height: 0;
	}

	/* IMAGE STYLES */
	.palette-container .item  svg {
		position: absolute;
		top: 10px;
		left: 10px;
	}

	/* CHECKED STYLES */

	.palette-container .item .palette-custom-radio ~ svg {
		opacity: 0;
		z-index: 3;
	}

	.palette-container .item .palette-custom-radio:checked ~ svg {
		opacity: 1;
	}
	.palette-container.palette-container-colors .item.item_radio_color_random .palette-custom-radio:checked ~ svg {
		margin-left: 14px;
		margin-top: 3px;
	}

	.palette-container .item .item-label {
		width: 100%;
		height: 100%;
		position: absolute;
		z-index: 5;
		cursor: pointer;
		text-align: center;
		line-height: 1.5;
		padding: 2% 0 0;
		font-weight: 700;
		font-size: 2em;
		color: #FF5722;
	}

	.palette-container .item .palette-custom-radio ~ .item-label {
		border:solid 5px transparent;
	}
	.palette-container .item .palette-custom-radio:checked ~ .item-label {
		border:solid 5px #fdbe3f;
	}

	.palette-container .item .item-label .img {
		height:90px;
	}


	/* CUSTOMIZE PALETTES */

	.palette-container.palette-container-colors .item {
		height: 55px;
		flex-basis: 33.33%;
	}
	.palette-container.palette-container-colors .item .item-label {
		height: 55px;
	}
	.palette-container.palette-container-colors .item svg {
		height: 30px;
		margin-top: -2px;
		margin-left: -10px;
	}

	.item_radio_element_uncheck .item-label svg,
	.item_radio_element_random .item-label svg {
		width: 110px;
		height: auto;
		position: initial;
	}






	/* BUTTONS */
	.btn-group-lg>.btn.btn_choose_element,
	.btn-lg.btn_choose_element {
		background-position: 2px 2px;
		background-repeat: no-repeat;
		background-size: 39px 43px;
		padding-left: 50px;
	}
	.btn_color{background-image: url('/assets/images/choose_color.svg');}
	.btn_hair{background-image: url('/assets/images/choose_hair.svg');}
	.btn_eye{background-image: url('/assets/images/choose_eye.svg');}
	.btn_eyeglasses{background-image: url('/assets/images/choose_eyeglasses.svg');}
	.btn_blouse{background-image: url('/assets/images/choose_blouse.svg');}
	.btn_beard{background-image: url('/assets/images/choose_beard.svg');}



	/* PAGE COLOR THEMES */
	/*
	body.theme-green{
		background-color: #a1fb39;
	}
	body.theme-green .alert-custom {
		border-color: #d43226;
		background-color: #FF5722;
	}
	body.theme-blue .alert-custom .alert-link,
	body.theme-blue.alert-custom .alert-link:hover {
		color:#00BCD4;
	}
	body.theme-green .custom_popup {
		border-color: #025f56;
		background-color: #009688;
	}
	body.theme-green .card.card-active,
	body.theme-green .card:hover{
		border-color: #009688;
	}
	body.theme-green .btn-warning{
		color: #212529;
		background-color: #a1fb39;
		border-color: #a1fb39;
	}
	body.theme-green .btn-warning:hover {
		color: #212529;
		background-color: #a1fb39;
		border-color: #a1fb39;
	}
	body.theme-green .popup_close {
		background-color:#a1fb39;
	}
	body.theme-blue .text-highlight {
		color:#a1fb39;
	}



	body.theme-blue{
		background-color: #00BCD4;
	}
	body.theme-blue .alert-custom {
		border-color: #FF9800;
		background-color: #FFEB3B;
	}
	body.theme-blue .alert-custom .alert-link,
	body.theme-blue.alert-custom .alert-link:hover {
		color:#00BCD4;
	}
	body.theme-blue .custom_popup {
		border-color: #025f56;
		background-color: #009688;
	}
	body.theme-blue .card.card-active,
	body.theme-blue .card:hover{
		border-color: #009688;
	}
	body.theme-blue .btn-warning{
		color: #212529;
		background-color: #00BCD4;
		border-color: #00BCD4;
	}
	body.theme-blue .btn-warning:hover {
		color: #212529;
		background-color: #00BCD4;
		border-color: #00BCD4;
	}
	body.theme-blue .popup_close {
		background-color:#00BCD4;
	}
	body.theme-blue .text-highlight {
		color:#00BCD4;
	}
*/



	@media screen and (min-width: 768px) {
		.palette-container .item {
			flex-basis: 33.33%;
		}
		.palette-container.palette-container-colors .item {
			flex-basis: 25%;
		}
		.palette-container.palette-container-colors .item .item-label {
			font-size: 1em;
		}
		.palette-container.palette-container-colors .item svg {
			height: 40px;
			margin-top: -2px;
		}
		.palette-container.palette-container-colors .item.item_radio_color_random .palette-custom-radio:checked ~ svg {
			margin-left: 40px;
		}

		.item_radio_element_uncheck .item-label svg,
		.item_radio_element_random .item-label svg {
			width: 110px;
			height: auto;
			position: initial;
		}


	}

	@media screen and (min-width: 1366px) {
		.palette-container .item {
			flex-basis: 10.0%;
		}
		.palette-container.palette-container-colors .item {
			flex-basis: 12.5%;
		}
		.palette-container.palette-container-colors .item svg {
			height: 40px;
			margin-top: -7px;
		}
		.palette-container.palette-container-colors .item.item_radio_color_random .palette-custom-radio:checked ~ svg {
			margin-left: 40px;
			margin-top: -1px;
		}

		.item_radio_element_uncheck .item-label svg,
		.item_radio_element_random .item-label svg {
			margin-left: -6px;
		}
	}


</style>
<div class="container">

	<div class="page-header">
		<img src="/assets/images/mascot_wizard_opt.svg" alt="">
		<h1 class="text-center"><?php echo $title; ?></h1>
	</div>
    <?php echo validation_errors(); ?>

    <?php $this->load->view('notifications.phtml'); ?>

    <?php //echo $avatar->getCssStyle(); ?>

	<div id="wrapper">

		<div class="alert text-white bg-dark" role="alert">
			<div>Wyczaruj swojego awatarka w <?php echo count($data)+1; ?> krokach.<br>Awatara możesz używać w serwisach społecznościowych, czatach, komunikatorach. Wszędzie tam, gdzie masz ochotę.</div>
		</div>

		<div class="form mb-3">
		<form id="form-wizard" method="post">

			<div class="row">

                <?php
                // Popupy z kaflami
                foreach($data as $d) {
                    $this->load->view('card_items.phtml', $d);
                }
                ?>

				<div class="col mb-3">
					<div id="finish_card" class="card h-100 text-white bg-dark">
						<span class="step_number text-title text-highlight">Krok 5</span>
						<img class="card-img-top p-3" src="/assets/images/choose_avatar.svg" alt="Choose avatar">
						<div class="card-body d-flex flex-column">
							<h5 class="card-title text-title mt-auto">Gotowe</h5>
							<p class="card-text mt-auto">Teraz możesz zobaczyć swoją postać</p>
							<a href="#" class="btn btn-warning btn-block mt-auto">Pokaż awatarka</a>
						</div>
					</div>
				</div>

			</div>

		</form>

		</div> <!-- /.form -->



        <?php //echo $svg_image_data; ?>

		<div class="row">
			<div class="col-md-3 mb-3 text-center" id="preview">
				<img src="" class="img-fluid rounded-circle">
			</div>
			<div class="col-md-9" id="result_url">
				<div class="alert alert-custom hidden" role="alert">
					<img class="glyphicon" src="/assets/images/mascot_alert_info_opt.svg" alt="Information icon">
					<div>
						Adres URL do Twojego awatara:<br>
						<small>(Kliknij w adres, aby otworzyć obrazek w nowym oknie)</small><br>
						<span class="text-break"></span>
					</div>
				</div>
			</div>
		</div>

	</div>

</div>


<?php
// Popupy z formularzami
foreach($data as $d) {
    $this->load->view('popup_items.phtml', $d);
}
?>

<div class="m-5"></div>

<script>
	var module_path = '<?php echo $module_path; ?>'
	var module_url = '<?php echo $module_url; ?>';


	$(function() {

		function openPopup(target) {

			$('.custom_popup').addClass('hidden')
			$('#'+target).removeClass('hidden')

			$([document.documentElement, document.body]).animate({
				scrollTop: $("#"+target).offset().top - 10
			}, 400);
		}

		function getRandomAvatar(){
			$.ajax({
				method: 'GET',
				url: module_url+'get_random/',
			})
			.done(function (data) {
				// console.log(data)
				let image_url = '<?php echo base_url("images/avatars/"); ?>'+data;
				$('#preview img').attr('src', image_url)

				$('#result_url span').html('<a href="'+image_url+'" class="alert-link" target="_blank">'+image_url+'</a>')
				$('#result_url .alert').removeClass('hidden')


			})
			.always(function() {
				//openPopup('preview');

			});
		}

		getRandomAvatar();

		// Aby nie submitować dwukrotnie
		$("#finish_card a").on('click', function(e){
			e.preventDefault();
		})
		$('#form-wizard').on('submit', function (e) {
			e.preventDefault()

			let hair = $("input[name='radio_hair']:checked").val()
			let blouse = $("input[name='radio_blouse']:checked").val()
			let eye = $("input[name='radio_eye']:checked").val()
			let eyeglasses = $("input[name='radio_eyeglasses']:checked").val()
			let hair_color = $("input[name='radio_hair_color']:checked").val()
			let eye_color = $("input[name='radio_eye_color']:checked").val()
			let blouse_color = $("input[name='radio_blouse_color']:checked").val()
			let eyeglasses_color = $("input[name='radio_eyeglasses_color']:checked").val()

			$.ajax({
				method: 'POST',
				url: module_url+'draw_avatar/',
				data: {
					hair: hair,
					blouse: blouse,
					eye: eye,
					eyeglasses: eyeglasses,
					eye_color: eye_color,
					hair_color: hair_color,
					blouse_color: blouse_color,
					eyeglasses_color: eyeglasses_color,
				},
				// data: $(this).serialize(),
				// dataType:"json",
			})
			.done(function (data) {
				// console.log(data)
				let image_url = '<?php echo base_url("images/avatars/"); ?>'+data;
				$('#preview img').attr('src', '/images/avatars/' + data)

				$('#result_url span').html('<a href="'+image_url+'" class="alert-link" target="_blank">'+image_url+'</a>')
				$('#result_url .alert').removeClass('hidden')


			})
			.always(function() {
				openPopup('preview');

			});

		})


		$('.popup_close').on('click', function (e) {
			$(this).parent().addClass('hidden')
		})

		$('.js-close').on('click', function (e) {
			$('#'+$(this).data('close')).addClass('hidden')

			let target = $(this).data('target');
			openPopup(target)
			$('.card').removeClass('card-active')
			$('#'+target).addClass('card-active')
		})

		$('.js-open-popup,.js-card-clickable').on('click', function (e) {
			e.preventDefault();
			openPopup($(this).data('target'));
		})
		$('#finish_card').on('click', function(e){
			$('#form-wizard').submit();
		})

	})
</script>