<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>-->
<!--<script src="/assets/js/popper.min.js"></script>-->
<!--<script src="/assets/js/bootstrap.min.js"></script>-->
<?php echo isset($module_js) && $module_js !='' ? '<script src="/assets/js/' . $module_js . '">' : ''; ?>
<style>
	.tooltip > .tooltip-inner {background-color: #f00 !important;}
	.tooltip > .tooltip-arrow { border-bottom-color:#f00 !important; }
</style>
<footer>
	FOOTER
</footer>
</body>
</html>
