<div class="container">
	
	<?php echo validation_errors(); ?>

	<?php $this->load->view('notifications.phtml'); ?>

	<div class="login-form">
	<?php echo form_open('admin_panel/login'); ?>
			<h2 class="text-center"><?php echo $title; ?></h2>       

			<div class="form-group">
				<?php echo form_label('Login', 'login'); ?>
				<?php echo form_input(['name' => 'login', 'id' => 'login', 'class' => 'form-control']); ?>
			</div>

			<div class="form-group">
				<?php echo form_label('Hasło', 'password'); ?>
				<?php echo form_input(['name' => 'password', 'id' => 'password', 'class' => 'form-control']); ?>
			</div>

			<div class="form-group">
				<button type="submit" class="btn btn-primary btn-block">Log in</button>
			</div>

			<!--
			<div class="clearfix">
				<label class="pull-left checkbox-inline"><input type="checkbox"> Remember me</label>
				<a href="#" class="pull-right">Forgot Password?</a>
			</div>
--> 
		</form>
		<!--
		<p class="text-center"><a href="#">Create an Account</a></p>
-->

	</div>

</div>
